# Generated by Django 2.0.1 on 2018-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=512, null=True)),
                ('address2', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('role', models.IntegerField(choices=[(0, 'CUSTOMER'), (1, 'Dealer-Sales Agent'), (2, 'Dealer-Manager'), (3, 'Dealer-Admin'), (4, 'Global Administrator')], default=0)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
    ]
